<a href="https://colab.research.google.com/github/muriukiian/Python-for-machine-learning---Basics/blob/main/Numpy_Numerical_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

In [1]:
!pip install numpy

In [2]:
import numpy as np

List vs Numpy time-taken

In [3]:
from time import process_time

Time taken by a list vs. by an array

In [79]:
python_list = [i for i in range(10000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

0.0011553710000029582


In [16]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array += 5
end_time = process_time()
print(end_time - start_time)

0.000202632000000591


Numpy Arrays

In [18]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [19]:
#numpy array
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

Creating a one dimensional array

In [21]:
a = np.array([1,2,3,4])
print(a)
a.shape

[1 2 3 4]


(4,)

2 dimensional array

In [27]:
b = np.array([(1,2,3,4), (2,3,4,5)])

In [28]:
print(b)
b.shape

[[1 2 3 4]
 [2 3 4 5]]


(2, 4)

In [29]:
c = np.array([(1,2,3,4), (5,6,7,8)], dtype = float)
print(c)
c.shape

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


(2, 4)

Initial Placeholders in numpy arrays.

In [30]:
#create a numpy array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Create a numpy array of ones.

In [31]:
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [34]:
#create an array of a particular value
d = np.full((5,4),5)
print(d)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [36]:
#create an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Create a numpy array with random values

In [39]:
b = np.random.random((3,4))
print(b)

[[0.14977221 0.47439934 0.80567666 0.61347726]
 [0.73577162 0.75561669 0.07442526 0.36472387]
 [0.86502384 0.25857371 0.98867458 0.21959246]]


In [41]:
#random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[98 89 82 95 20]
 [74 30 99 67 91]
 [34 81 82 86 46]]


In [50]:
# create an array of evenly spaced values ----> specifying the number of values required.
d = np.linspace(10,30,3)
print(d)

[10. 20. 30.]


In [51]:
#array of evenly spaced values ----> specifying the step
a = np.arange(10,30,3)
print(a)

[10 13 16 19 22 25 28]


In [53]:
#convert a list to a numpy array
list2 = [10,20,30,40,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

Analysing a numpy array

In [55]:
c = np.random.randint(10,90,(5,5))
print(c)

[[48 10 68 38 46]
 [58 13 41 40 84]
 [69 42 46 57 32]
 [18 87 36 25 39]
 [78 62 41 79 69]]


In [56]:
#array dimension
c.shape

(5, 5)

In [57]:
#number of dimensions
print(c.ndim)

2


In [58]:
#number of elements in an array
print(c.size)

25


In [59]:
#checking the data type of values in the array
print(c.dtype)

int64


Mathematical operations on a numpy array

In [60]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2)  #+ sign concatenates / joins 2 lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [63]:
a= np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[6 7 9]
 [1 4 6]
 [0 1 0]]
[[14 19 16]
 [19 15 10]
 [10 12 19]]


In [64]:
print(a + b)
print(a - b)
print(a / b)
print(a * b)

[[20 26 25]
 [20 19 16]
 [10 13 19]]
[[ -8 -12  -7]
 [-18 -11  -4]
 [-10 -11 -19]]
[[0.42857143 0.36842105 0.5625    ]
 [0.05263158 0.26666667 0.6       ]
 [0.         0.08333333 0.        ]]
[[ 84 133 144]
 [ 19  60  60]
 [  0  12   0]]


In [67]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(11,20,(3,3))
print(a)
print(b)

[[1 9 3]
 [4 7 1]
 [2 1 6]]
[[11 12 13]
 [18 15 19]
 [16 11 17]]


In [68]:
print(np.add(a,b))


[[12 21 16]
 [22 22 20]
 [18 12 23]]


In [69]:
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[-10  -3 -10]
 [-14  -8 -18]
 [-14 -10 -11]]
[[ 11 108  39]
 [ 72 105  19]
 [ 32  11 102]]
[[0.09090909 0.75       0.23076923]
 [0.22222222 0.46666667 0.05263158]
 [0.125      0.09090909 0.35294118]]


Array manipulation


In [70]:
a  = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[0 6 2]
 [7 2 1]]
(2, 3)


In [72]:
#transpose
trans = np.transpose(a)
print(trans)
print(trans.shape)

[[0 7]
 [6 2]
 [2 1]]
(3, 2)


In [73]:
a  = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[9 8 9]
 [4 5 3]]
(2, 3)


In [74]:
trans2 = a.T
print(trans2)
print(trans2.shape)

[[9 4]
 [8 5]
 [9 3]]
(3, 2)


In [75]:
#reshaping array
b = np.random.randint(0,10,(2,3))
print(b)
print(b.shape)

[[7 9 4]
 [7 8 3]]
(2, 3)


In [76]:
c = b.reshape(3,2)
print(c)
c.shape

[[7 9]
 [4 7]
 [8 3]]


(3, 2)